#!/bin/bash

# Define the version of Mini-Tools
VERSION="1.0.0"

# Function to display the version
show_version() {
    echo "Mini-Tools version $VERSION"
}

# Function to display help
show_help() {
    echo "Usage: minitools [options]"
    echo
    echo "Options:"
    echo "  -v, --version        Display the version of Mini-Tools"
    echo "  -l, --list-tools     List available tools and unavailable tools"
    echo "  -up, --update        Update Mini-Tools from the repository"
    echo "  -h, --help           Display this help"
}

# Function to list available tools
list_tools() {
    local script_dir
    script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
    if [[ -f "$script_dir/mini_tools_list.txt" ]]; then
        printf "%-20s %-20s %-10s %-50s\n" "Tool" "Commande" "Version" "Description"
        printf "%-20s %-20s %-10s %-50s\n" "----" "--------" "-------" "-----------"
        while IFS= read -r tool; do
            name=$(echo "$tool" | awk -F' ' '{print $1}')
            file=$(echo "$tool" | awk -F'"' '{print $2}')
            version=$(echo "$tool" | awk -F'[()]' '{print $2}')
            description=$(echo "$tool" | awk -F'[][]' '{print $2}' | fold -s -w 50)
            first_line=true
            while IFS= read -r line; do
                if $first_line; then
                    if [[ -f "$script_dir/$file" ]]; then
                        printf "\e[32m%-20s\e[0m %-20s %-10s %-50s\n" "$name" "$file" "$version" "$line"
                    else
                        printf "\e[31m%-20s\e[0m %-20s %-10s %-50s\n" "$name" "$file" "$version" "$line"
                    fi
                    first_line=false
                else
                    printf "%-20s %-20s %-10s %-50s\n" "" "" "" "$line"
                fi
            done <<< "$description"
            printf "\n"
        done < "$script_dir/mini_tools_list.txt"
        printf "\e[32mAvailable tools\e[0m\n"
        printf "\e[31mUnavailable tools\e[0m\n"
    else
        echo "Le fichier mini_tools_list.txt est introuvable."
    fi
}

# Function to update Mini-Tools from the repository
update_tools() {
    local repo_url="https://github.com/DIGYSKY/Mini-Tools.git"
    local script_dir
    script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
    echo "Updating Mini-Tools from $repo_url in the directory $script_dir"
    cd "$script_dir" || { echo "Unable to change directory to $script_dir"; exit 1; }
    git pull "$repo_url"
    if [[ $? -eq 0 ]]; then
        echo "Update successful."
    else
        echo "Update failed."
    fi
}

# Parse command line arguments
case "$1" in
    -v|--version)
        show_version
        ;;
    -l|--list-tools)
        list_tools
        ;;
    -up|--update)
        update_tools
        ;;
    -h|--help)
        show_version
        echo
        show_help
        ;;
    *)
        show_version
        echo
        show_help
        ;;
esac
