#!/bin/bash

# Define the version of Mini-Tools
VERSION="1.0.0"

# Function to display the version
show_version() {
    echo "Mini-Tools version $VERSION"
}

# Function to display help
show_help() {
    echo "Usage: minitools [options]"
    echo
    echo "Options:"
    echo "  -v, --version        Display the version of Mini-Tools"
    echo "  -l, --list-tools     List available tools in mini_tools_list.txt"
    echo "  -up, --update        Update Mini-Tools from the repository"
    echo "  -h, --help           Display this help"
}

# Function to list available tools
list_tools() {
    if [[ -f "mini_tools_list.txt" ]]; then
        echo "Available tools:"
        while IFS= read -r tool; do
            echo "- $tool"
        done < "mini_tools_list.txt"
    else
        echo "The file mini_tools_list.txt is not found."
    fi
}

# Function to update Mini-Tools from the repository
update_tools() {
    local repo_url="https://github.com/DIGYSKY/Mini-Tools.git"
    local script_dir
    script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
    echo "Updating Mini-Tools from $repo_url in the directory $script_dir"
    cd "$script_dir" || { echo "Unable to change directory to $script_dir"; exit 1; }
    git pull "$repo_url"
    if [[ $? -eq 0 ]]; then
        echo "Update successful."
    else
        echo "Update failed."
    fi
}

# Parse command line arguments
case "$1" in
    -v|--version)
        show_version
        ;;
    -l|--list-tools)
        list_tools
        ;;
    -up|--update)
        update_tools
        ;;
    -h|--help)
        show_version
        echo
        show_help
        ;;
    *)
        show_version
        echo
        show_help
        ;;
esac
